#!/bin/sh
cp show-notifications.dockitem ~/.config/plank/dock1/launchers/
sudo cp show-notifications /usr/local/bin/
sudo cp show-notifications.dockitem /usr/lib/plugs/pantheon/tweaks/
sudo cp show-notifications.desktop /usr/share/applications/
sudo cp show-notifications.png /usr/share/pixmaps/
echo "Instalado"
